### PR TITLE
NXP-29566: Fix nuxeoctl register prompt

### PR DESCRIPTION
**Pull request by kevinleturc**

### CODE REVIEW

**Review by ataillefer — APPROVED** [review]

**Comment by ataillefer** [comment]
Note: a comment would be nice to explain why we need to force the linking of stdin, stdout, stderr since we're running a background process.

**Review by ataillefer — APPROVED** [review]

**Review by bdelbosc — COMMENTED** [review]
I find it a bit weird, normally stdout and stderr of a background process don't need to be redirected. 
About the stdin, what is happening if it is close just after the invocation, which should be the case if you run nuxeoctl within an ssh command (`ssh $HOST nuxeoctl CMD`)?

**Comment by efge** [comment]
Agreed, I'm dubious about the fact that `<&0 >&1 2>&2` has any effect, it means redirect fd 0, 1 and 2 to themselves which seems a nop to me.

**Comment by kevinleturc** [comment]
Indeed for `stdout` and `stderr` on background processes, there's only `stdin` which is detached for a background process, so we just need `<&0`. In other words, when the process is in the foreground, its `stdin` under `/proc/PID/fd/0` is linked to the `stdin` of the process launching it. This is not the case when the process is in the background, thus we need to link it with `<$0`.

I will test the ssh command scenario.

**Comment by kevinleturc** [comment]
When running:
```
ssh $HOST nuxeoctl register
```
nuxeoctl will hang and never give back the prompt, I'm trying to understand what can we do.

Otherwise, adding the `-t` option is working.

**Comment by kevinleturc** [comment]
I push a change to remove stdout and stderr redirection and an additional commit to make the ssh command work.

**Comment by efge** [comment]
`<&0` means copy fd `0` to the fd for stdin, which is 0. So it's a nop. Where does this idiom come from and are you sure it works?

**Review by ataillefer — APPROVED** [review]

**Review by troger — APPROVED** [review]

**Pull request merged**
