### PR TITLE
NXP-21432: Update AWS SDK version

### PR DESCRIPTION
**Pull request by loopingz**

### CODE REVIEW

**Comment by efge** [comment]
Please fill in the fix version in the NXP ticket and mention the exact library version used in the description.

**Comment by efge** [comment]
👍

**Comment by jcarsique** [comment]
:+1:

**Comment by loopingz** [comment]
Sorry guys, updated it again with latest version, and fix the nuxeo-core-binarymanager-cloud at the same time

**Comment by efge** [comment]
Sure. You can squash and merge of course.

**Pull request closed without merging**
