### PR TITLE
NXP-20120: use the popup page

### PR DESCRIPTION
**Pull request by tmartins**
to render the Add New Entry popup

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/nuxeo/nuxeo/pull/162" target="_blank">ReviewNinja

**Comment by troger** [comment]
👍

**Comment by atchertchian** [comment]
:+1:

**Comment by ffjdm** [comment]
Closing PR since it has not been merged and is sitting for a long time. Need a new TnP before merging.

**Pull request closed without merging**
