### PR TITLE
NXP-23947: do not handle non dirty references when updating entry in …

### PR DESCRIPTION
**Pull request by funshodavid**
…mongoDB

### CODE REVIEW

**Comment by akervern** [comment]
👍 
Maybe it could be interesting to cover it with a unit test, no?

**Comment by akervern** [comment]
👍

**Comment by efge** [comment]
👍 but please add a unit test asap

**Comment by funshodavid** [comment]
T&P successful: https://qa.nuxeo.org/jenkins/view/TestAndPush/job/TestAndPush/job/ondemand-testandpush-fdavid-master/325/

**Pull request merged**
