### PR TITLE
NXP-29626: fix FormData#getFormFields NPE when request contains binar…

### PR DESCRIPTION
**Pull request by atchertchian**
…y content

### CODE REVIEW

**Review by NourNuxeo — APPROVED** [review]

**Review by NourNuxeo — COMMENTED** [review]
How about unit testing the change?

**Comment by atchertchian** [comment]
> How about unit testing the change?

Of course, i would have gladly added a non-regression unit test.
And then i looked at the src/test/java content, and i felt that i already had a fair share of initiating tests on legacy code these days ;)

More seriously, this is a tiny part of the 4 PRs that need to be merged to achieve the actual goal: i'll see if i can do something easily, otherwise i'll probably defer this bugfix and use the non-buggy non-generic api to retrieve form field values.

Also, i'm pretty sure that this method has never really been used since it was created 10 years ago (very standard use case of multipart form fields retrieval, actually buggy when there is binary content in the request...)

**Comment by atchertchian** [comment]
Done, note that unit test did not reproduce the issue with "real-life" org.apache.commons.fileupload.disk.DiskFileItem usage

**Review by NourNuxeo — APPROVED** [review]
💪 💪

**Review by bdelbosc — APPROVED** [review]

**Pull request merged**
