### PR TITLE
fix-NXP-21612-fix-grammar-for-label.content.emptyFolder-8.10

### PR DESCRIPTION
**Pull request by jfletcher-nuxeo**
Fix grammar in message.

### CODE REVIEW

**Comment by efge** [comment]
👍

**Comment by jcarsique** [comment]
:+1: but it seems that there's also a test to accordingly adapt:
`./nuxeo-distribution/nuxeo-jsf-ui-webdriver-tests/src/test/java/org/nuxeo/ftest/cap/ITPublishDocumentTests.java:180:        assertTrue(driver.getPageSource().contains("This folder contains no document"));
`
https://github.com/nuxeo/nuxeo/blob/master/nuxeo-distribution/nuxeo-jsf-ui-webdriver-tests/src/test/java/org/nuxeo/ftest/cap/ITPublishDocumentTests.java#L180

**Comment by jfletcher-nuxeo** [comment]
Thanks @jcarsique I hadn't even considered this!

**Comment by atchertchian** [comment]
@jfletcher-nuxeo please reference the jira issue in commit messages, i'll test&push the change if you want. And the test uses "contains" it was not absolutely needed to be updated

**Comment by atchertchian** [comment]
will be handled on master and 8.10 in other branches

**Pull request closed without merging**
