### PR TITLE
9.10-HF/fix-NXP-28339-user-groups

### PR DESCRIPTION
**Pull request by troger**

### CODE REVIEW

**Comment by troger** [comment]
T&P: https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-troger-9.10/67/

**Comment by RSalem07** [comment]
I think as its a cherry pick of `10.10` i made the review mainly on https://github.com/nuxeo/nuxeo/pull/3620#pullrequestreview-335762471  :)

**Comment by troger** [comment]
T&P following changes: https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-troger-9.10/69/

**Comment by troger** [comment]
T&P following changes: https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-troger-9.10/73/

**Pull request merged**
