### PR TITLE
NXP 28595: Improvement s3binarymanager junit update aws config

### PR DESCRIPTION
**Pull request by doulba**
This PR replaces #3718

### CODE REVIEW

**Comment by efge** [comment]
Hi @doulba, if this is ready for review then please move the PR out of the Draft state.

**Comment by doulba** [comment]
> Hi @doulba, if this is ready for review then please move the PR out of the Draft state.

Hello, i'm waiting for some information from cloud.
This PR is still in Draft state.

**Comment by doulba** [comment]
HI @efge ,

This PR is ready to be reviewed.
when running some test , i have found that prefix is not work properly for this tests
- TestS3DirectBatchHandlerWithSSEAndPolicy
- TestS3DirectBatchHandlerWithSSE

**Comment by ataillefer** [comment]
Thanks @doulba, we'll take it from here.
Indeed some work needs to be done on the prefix and cleanup mechanism.

The important part is that it has been validated that the S3 tests can work in Jenkins X thanks to:
- the AWS buckets, credentials and key rotation, see https://jira.nuxeo.com/browse/NXBT-3222
- the changes from this PR to rely on environment variables instead of harcoded names

**Pull request closed without merging**
