### PR TITLE
NXP-29504: fix avro duplicate contributions in CoreBulkFeature tests

### PR DESCRIPTION
**Pull request by atchertchian**
CoreIOFeature and RuntimeStreamFeature both include avro dependencies

### CODE REVIEW

**Comment by atchertchian** [comment]
I noticed this one because it's affecting one of the explorer unit tests on runtime startup messages.

There is actually a number of tests affected by the fact that there are duplicate components being deployed, these were not as visible before changes for NXP-29504.

The most visible one is avro since it's used in a lot of tests, and is not actually impacting as long as tests are not checking runtime messages, but it might be useful to clean them up if there is an opportunity.

Grepping nuxeo tests console at https://jenkins.platform.dev.nuxeo.com/job/nuxeo/job/nuxeo/job/master/599/consoleText, setting avro aside:

```
Duplicate component name: service:org.nuxeo.ecm.directory.storage.cache
Duplicate component name: service:org.nuxeo.ecm.directory.ldap.storage
Duplicate component name: service:org.nuxeo.ecm.core.work.test.default.queuing
Duplicate component name: service:org.nuxeo.usermapper.testContribs
Duplicate component name: service:org.nuxeo.ecm.automation.server.auth.config
Duplicate component name: service:org.nuxeo.ecm.platform.ui.web.auth.defaultConfig
Duplicate component name: service:org.nuxeo.elasticsearch.test.contrib
Duplicate component name: service:org.nuxeo.ecm.liveconnect.workmanager
Duplicate component name: service:org.nuxeo.ecm.liveconnect.box.core.cache
Duplicate component name: service:org.nuxeo.ecm.liveconnect.box.core.pageprovider
Duplicate component name: service:org.nuxeo.ecm.platform.publisher.contrib
Duplicate component name: service:org.nuxeo.ecm.platform.audit.core.types-contrib
```

**Comment by atchertchian** [comment]
> ok but this is unclear to me in what it is related to Avro, maybe it deserves an explanation in the NXP or commit message

Ok i can add more info, the description of this PR is actually in the commit message: RuntimeStreamFeature deploys avro, and CoreIOFeature too.
It's indeed not easy to track down duplicate components being deployed when mixing different features.
What would make this even clearer, please?

**Comment by atchertchian** [comment]
I added a big comment on https://jira.nuxeo.com/browse/NXP-29504, please tell if that's explicit enough @bdelbosc

**Comment by bdelbosc** [comment]
Thanks this is perfectly clear now with the error messages related to Avro.

**Pull request merged**
