### PR TITLE
NXP-28635: Use save param

### PR DESCRIPTION
**Pull request by michaelva**

### CODE REVIEW

**Comment by troger** [comment]
Worth adding a simple unit test.

**Comment by efge** [comment]
If this is merged for 10.10 then this should be merged for master too. I agree that we would need a unit test but this can be done in a separate step now. We should have parity in master for all code that is in a maintenance branch.

**Comment by michaelva** [comment]
I would gladly merge but need one more review/approval to do so :)

**Comment by michaelva** [comment]
@efge I don't believe it changes the behavior. The save param default value is true so unless it was explicitly set to false in chains/scripts that use the operation, the behavior remains unchanged. If the param was set to false, the document was saved anyway which wasn't the expected result.

**Comment by efge** [comment]
@michaelva please also resolve the corresponding NXP ticket as well once this is merged

**Pull request merged**
