### PR TITLE
NXP-29275: Update nuxeo-retentionrules-view-layout.html

### PR DESCRIPTION
**Pull request by ThibArg**
I even tried to format the addition as the others <nuxeo-data-table-column ;-)

### CODE REVIEW

**Comment by kevinleturc** [comment]
Hello @ThibArg, thanks for the contribution, do you have a NXP driving this change? Also, did you run a T&P? You can use mine: https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-kleturc-10.10/

**Comment by ThibArg** [comment]
Ha no, I did not. Doing it.

**Comment by kevinleturc** [comment]
Your T&P has succeeded: https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-kleturc-10.10/83/ 🔵 🎉 

One more details and we're good to merge, can you put the NXP ticket in the commit message please?

**Comment by ThibArg** [comment]
Yeah, sorry I messed up the commit message. It is fixed.

**Comment by ThibArg** [comment]
Thanks, my pleasure :-)

**Pull request merged**
