### PR TITLE
NXP-20228: add test parameters; include test parameters on SystemPathExistTester

### PR DESCRIPTION
**Pull request by tiagocardoso**
For a code review

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/nuxeo/nuxeo/pull/178" target="_blank">ReviewNinja

**Comment by efge** [comment]
👍

**Comment by efge** [comment]
Ok thanks for the rename! Looks good.

**Comment by troger** [comment]
👍

**Pull request closed without merging**
