### PR TITLE
NXP-31326: Upgrade commons-text

### PR DESCRIPTION
**Pull request by bdelbosc**

### CODE REVIEW

**Review by guirenard — APPROVED** [review]

**Review by kevinleturc — APPROVED** [review]

**Comment by sgammon** [comment]
hi, why did this get merged over #5177 / #5178 ?

**Comment by guirenard** [comment]
Hi @sgammon, we need a reference to our Jira in the commit message

**Comment by sgammon** [comment]
i'm not able to file tickets in Jira... how would i reference a CVE if i want to contribute? are contributions accepted? just curious for some guidance @guirenard

**Comment by bdelbosc** [comment]
Hi @sgammon, sorry I saw your contribution after I made mine, 
otherwise we could have created the ticket during the review.
Thanks again for your contribution.
Regards

**Comment by sgammon** [comment]
@bdelbosc thank you for clarifying and obviously for patching so quickly, the CVE hasn't even cleared analysis yet but looks nasty 👍🏻

**Pull request merged**
