### PR TITLE
NXP-24961: Add privileged user directories access

### PR DESCRIPTION
**Pull request by espa77**

### CODE REVIEW

**Comment by efge** [comment]
👍

**Comment by efge** [comment]
Code is good but this needs a non-regression test.

**Comment by atchertchian** [comment]
Is it possible to have a non-regression test with this change?

**Comment by espa77** [comment]
I have no idea how to write a non-regression test for this... Any pointer would be helpful.

**Comment by funshodavid** [comment]
T&P successful : https://qa.nuxeo.org/jenkins/view/TestAndPush/job/TestAndPush/job/ondemand-testandpush-fdavid-master/391/

**Comment by covolution** [comment]
:+1:

**Comment by pierre-gautier** [comment]
👍

**Pull request merged**
