### PR TITLE
NXP-27386: fix Redis pubsub subscriber reentrancy to Redis

### PR DESCRIPTION
**Pull request by efge**
https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume/690/

### CODE REVIEW

**Comment by troger** [comment]
I'm wondering, looking at the diff, for each `onMessage` we are using a thread from the pool. Wouldn't that be more efficient to have a separate thread for the subscribe part but still use the same thread for the publishing? I would think we are doing less subscribe than publish.

Not sure it's possible or better...

**Comment by bdelbosc** [comment]
:+1:

**Comment by bdelbosc** [comment]
@troger there will be only one thread created used for the onMessage, the thread will be cached for 60s

**Comment by troger** [comment]
:+1:

**Comment by ataillefer** [comment]
:+1:

**Pull request merged**
