### PR TITLE
NXP-29801: sonar cleanup

### PR DESCRIPTION
**Pull request by efge**

### CODE REVIEW

**Comment by efge** [comment]
T&P ok https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume/856/

**Review by fsrrt — CHANGES_REQUESTED** [review]
@MIUI 12 GLOBAL UPDATE @

**Review by fsrrt — APPROVED** [review]

**Comment by efge** [comment]
Blocked for spamming.

**Review by kevinleturc — DISMISSED** [review]
Nice cleanup 👍

**Review by kevinleturc — APPROVED** [review]

**Review by troger — APPROVED** [review]

**Pull request merged**
