### PR TITLE
Fix nxp 29726 use of custom retention end action

### PR DESCRIPTION
**Pull request by RSalem07**
PR is failing with some errors on kafka, will be stopped and re-launched
Some random errors are observed on the new CI/CD build.

I started new one on TestAndPush: https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-saouana/249/ and it's OK.

### CODE REVIEW

**Review by efge — APPROVED** [review]

**Review by nmpcunha — DISMISSED** [review]
LGTM 👍🏼 

If I understood correctly, @jaubenque is OK with this change.

**Comment by RSalem07** [comment]
@nmpcunha thanks, 

Yes exactly sharing the implementation rules with Julien on slack and he validated them, IIRC @lisamcintyre proposed to update the ticket with my Slack description

**Review by nmpcunha — APPROVED** [review]

**Comment by efge** [comment]
@RSalem07 why the force-push and re-review please? What changed?

**Comment by RSalem07** [comment]
sorry about it @efge I didn't change any thing since your last approve it was just rebasing master. 
thx

**Review by efge — APPROVED** [review]

**Comment by efge** [comment]
> sorry about it @efge I didn't change any thing since your last approve it was just rebasing master.
> thx

@RSalem07 ok no problem, note that a simple rebase is not needed unless you need to re-trigger the automated checks, otherwise the "Rebase and merge" button will do it for you.

**Pull request merged**
