### PR TITLE
NXP-25809: filter null values for files:files properties in resolver

### PR DESCRIPTION
**Pull request by funshodavid**

### CODE REVIEW

**Comment by kevinleturc** [comment]
👍

**Comment by efge** [comment]
I don't like the fact that we hardcode `file` / `files`. Customers or even Nuxeo could have other schemas that contain blobs. Can't we be more generic?

**Comment by funshodavid** [comment]
T&P : https://qa.nuxeo.org/jenkins/view/TestAndPush/job/TestAndPush/job/ondemand-testandpush-fdavid-master/504/

**Comment by efge** [comment]
👍

**Pull request merged**
