### PR TITLE
fix-NXP-23772-Fix typo in error message.

### PR DESCRIPTION
**Pull request by jfletcher-nuxeo**

### CODE REVIEW

**Comment by guirenard** [comment]
Please refer a NXP issue in your commit message.

**Comment by atchertchian** [comment]
:+1:

**Comment by guirenard** [comment]
:+1: thanks for adding the NXP ticket to the commit message that we can have a comment in JIRA and follow up fix versions

**Comment by guirenard** [comment]
:+1:

**Pull request merged**
