### PR TITLE
NXP-21368: Remove DownloadService cache settings override

### PR DESCRIPTION
**Pull request by vpasquier**

### CODE REVIEW

**Comment by vpasquier** [comment]
https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-vpasquier should have created the PR itself. https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-vpasquier/7 is blue though (checking the T&P configuration potentially not up to date)

**Comment by efge** [comment]
Please explain in the NXP what is the resulting caching configuration (headers and what extension points configure it) for a stock Nuxeo server. The NXP says we'll have `Cache-Control: private, max-age=60, must-revalidate` but it's not explained how. This must be made very clear in the NXP itself. The NXP must not talk about "potential solutions" but about what is actually implemented. Please change the description of the ticket to reflect what is actually being committed.

 I don't agree with removing all caching for "security reasons" if these reasons are not explained. We cannot afford to not cache with Etag etc a bunch of resources.

**Comment by vpasquier** [comment]
So ticket has been clarified and cache was not activated by default for this reason: https://www.owasp.org/index.php/Session_Management_Cheat_Sheet#Web_Content_Caching

**Comment by efge** [comment]
👍

**Comment by akervern** [comment]
:+1:

**Pull request merged**
