### PR TITLE
NXP-27209: clean up redundant generic types

### PR DESCRIPTION
**Pull request by efge**

### CODE REVIEW

**Comment by kevinleturc** [comment]
👍

**Comment by pierre-gautier** [comment]
👍

**Comment by pierre-gautier** [comment]
thanks !

**Comment by kevinleturc** [comment]
👍

**Comment by pierre-gautier** [comment]
👍

**Comment by efge** [comment]
https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume/674/

**Pull request merged**
