### PR TITLE
fix-NXP-27131-sanitize-Document.AddPermission-email

### PR DESCRIPTION
**Pull request by ataillefer**
Do not merge, T&P to be run.

### CODE REVIEW

**Comment by efge** [comment]
👍

**Comment by troger** [comment]
T&P: https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-ataillefer-1/9/

**Comment by kevinleturc** [comment]
👍

**Comment by troger** [comment]
:+1:

**Comment by efge** [comment]
👍

**Pull request merged**
