### PR TITLE
NXP-26891: MongoDBChecker re-uses config Backport

### PR DESCRIPTION
**Pull request by covolution**

### CODE REVIEW

**Comment by efge** [comment]
👍

**Comment by covolution** [comment]
T & P is going here: https://qa2.nuxeo.org/jenkins/view/TestAndPush/job/TestAndPush/job/ondemand-testandpush-gethin-10.10/

**Comment by covolution** [comment]
Successful T & P, just need to merge.

**Comment by covolution** [comment]
:+1:

**Pull request merged**
