### PR TITLE
NXP-29261: Implement a way to contribute MongoDB indexes

### PR DESCRIPTION
**Pull request by kevinleturc**
T&P: https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-kleturc-10.10/166/

### CODE REVIEW

**Comment by kevinleturc** [comment]
T&P ok.

**Review by troger — APPROVED** [review]

**Review by ataillefer — DISMISSED** [review]

**Comment by kevinleturc** [comment]
T&P: https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-kleturc-10.10/167

**Comment by kevinleturc** [comment]
T&P: https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-kleturc-10.10/168

**Comment by kevinleturc** [comment]
T&P: https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-kleturc-10.10/169

**Review by ataillefer — APPROVED** [review]

**Review by troger — APPROVED** [review]

**Pull request merged**
