### PR TITLE
NXP-24449: strip force anonymous login parameter from saved start page

### PR DESCRIPTION
**Pull request by nelsonsilva**

### CODE REVIEW

**Comment by efge** [comment]
👍

**Comment by efge** [comment]
Although I'd have loved a unit test as well 😁

**Comment by nelsonsilva** [comment]
Done @efge ;) Added simple anonymous auth test too.

**Comment by nelsonsilva** [comment]
🔵 https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-nsilva/124/

**Comment by kevinleturc** [comment]
👍

**Pull request merged**
