### PR TITLE
NXP-26637: introduce a specific handler for user and group aggregate …

### PR DESCRIPTION
**Pull request by guirenard**
…widget to be able to resolve prefixed ids

### CODE REVIEW

**Comment by guirenard** [comment]
T&P will follow if 1st review is ok

**Comment by atchertchian** [comment]
:+1: LGTM!

A few comments:
- For UIUserAndGroupSelectItems, it seems like a lot of code is duplicated, i assume you do not really have a choice (just in case there is another way)
- the fact that the select item labels are hardcoded removes a configuration possibility (for people who who'd like to customize and show the user email for instance) but maybe it's overkill to refine this -- note we could use the methods that have been added for this on some templates, see https://github.com/nuxeo/nuxeo/blob/release-10.10/nuxeo-jsf/nuxeo-platform-webapp-base/src/main/resources/web/nuxeo.war/widgets/user_group_display_template.xhtml#L39 but also https://github.com/nuxeo/nuxeo/blob/release-10.10/nuxeo-jsf/nuxeo-platform-webapp-base/src/main/resources/web/nuxeo.war/widgets/user_group_display_template.xhtml#L43, as well as https://github.com/nuxeo/nuxeo/blob/release-10.10/nuxeo-jsf/nuxeo-platform-webapp-base/src/main/resources/web/nuxeo.war/widgets/user_group_display_template.xhtml#L75 for groups. These could be exposed as "default expressions" on the widget type configuration if you agree
- as previously discussed, this widget could be added to the layout-demo showcase (for reference and functional tests)

**Comment by atchertchian** [comment]
(above changes validated by T&P)

**Comment by guirenard** [comment]
:+1:

**Comment by troger** [comment]
:+1:

**Pull request merged**
