### PR TITLE
NXP-27075: switch to jaxen 1.2.0

### PR DESCRIPTION
**Pull request by pierre-gautier**

### CODE REVIEW

**Comment by efge** [comment]
Ok but waiting for T&P

**Comment by pierre-gautier** [comment]
https://qa.nuxeo.org/jenkins/view/TestAndPush/job/TestAndPush/job/ondemand-testandpush-pierregautier-jdk11-aws/281

**Comment by efge** [comment]
T&P ok

**Comment by efge** [comment]
👍

**Comment by pierre-gautier** [comment]
👍

**Pull request merged**
