### PR TITLE
NXP-25251: Implement deletion bulk action

### PR DESCRIPTION
**Pull request by funshodavid**
T&P failing on MongoDB with unrelated issue (at first sight) : https://qa.nuxeo.org/jenkins/view/TestAndPush/job/TestAndPush/job/ondemand-testandpush-fdavid-master/590/artifact/nuxeo-distribution/nuxeo-jsf-ui-hotreload-tests/target/tomcat/log/server.log

### CODE REVIEW

**Comment by kevinleturc** [comment]
:+1:

**Comment by efge** [comment]
👎 
- must deal with proxies
- recompute the version series on each document removed is too costly (does a query for each)
Dealing with both these "relational" problems is hard must must be suitably done if we want performance.

**Comment by covolution** [comment]
:+1:

**Comment by pierre-gautier** [comment]
👍

**Pull request merged**
